// Generated by tools/gen_segments.py; do not edit by hand.
// Segment outlines from the "7-Segment" font by Jan Bobrowski (~jb),
// (https://torinak.com/font/7-segment), SIL Open Font License 1.1,
// de-skewed to upright. Coordinates are 0..1000, y = 0 at the top.
#pragma once

static const int16_t SEG_POLY_A[] = { 720, 125, 276, 125, 88, 29, 135, 13, 187, 3, 243, 0, 758, 0, 806, 3 };
static const int16_t SEG_POLY_B[] = { 758, 145, 852, 10, 933, 38, 983, 76, 1000, 125, 999, 451, 917, 483, 756, 421 };
static const int16_t SEG_POLY_C[] = { 758, 581, 916, 518, 999, 551, 1000, 875, 984, 925, 935, 964, 853, 991, 756, 857 };
static const int16_t SEG_POLY_D[] = { 276, 875, 720, 875, 806, 999, 758, 1000, 243, 1000, 187, 997, 136, 988, 89, 973 };
static const int16_t SEG_POLY_E[] = { 241, 858, 54, 954, 24, 931, 6, 904, 1, 875, 0, 551, 82, 518, 243, 581 };
static const int16_t SEG_POLY_F[] = { 241, 421, 83, 483, 0, 451, 1, 125, 7, 97, 25, 71, 55, 47, 243, 143 };
static const int16_t SEG_POLY_G[] = { 117, 500, 276, 438, 723, 438, 881, 500, 723, 562, 276, 562 };

static const int16_t *const SEG_POLYS[7] = {
  SEG_POLY_A, SEG_POLY_B, SEG_POLY_C, SEG_POLY_D, SEG_POLY_E, SEG_POLY_F, SEG_POLY_G,
};
static const uint8_t SEG_POLY_LEN[7] = { 8, 8, 8, 8, 8, 8, 6 };
