#!/usr/bin/env python3
"""Extracts 7-segment outlines from the "7-Segment" font by Jan Bobrowski
(~jb, https://torinak.com/font/7-segment, SIL Open Font License 1.1) and writes them
into src/c/segments.h as polygons normalized to 0..1000 in both axes.

The font is italic; outlines are de-skewed to upright. Quadratic curves are
flattened into short line segments. Usage:

    curl -sLo /tmp/7segment.ttf https://torinak.com/font/7segment.ttf
    python3 tools/gen_segments.py /tmp/7segment.ttf
"""
import math
import sys
from pathlib import Path

from fontTools.ttLib import TTFont

# Segment letter -> component glyph used by the font's "8".
SEGMENTS = {
    "A": "uni203E", "B": "uniF062", "C": "comma", "D": "underscore",
    "E": "uniF065", "F": "quotesingle", "G": "hyphen",
}
CURVE_STEPS = 3


def contour_points(glyf, name):
    coords, ends, flags = glyf[name].getCoordinates(glyf)
    assert len(ends) == 1, name
    return [(coords[i][0], coords[i][1], bool(flags[i] & 1)) for i in range(ends[0] + 1)]


def flatten(pts):
    """Turns a closed TrueType contour (on/off-curve points) into a polygon."""
    n = len(pts)
    start = next(i for i, p in enumerate(pts) if p[2])
    pts = pts[start:] + pts[:start]
    out = []
    i = 0
    while i < n:
        x, y, _ = pts[i]
        out.append((x, y))
        nx, ny, non = pts[(i + 1) % n]
        if non:
            i += 1
            continue
        # Off-curve control point; the end is the next on-curve point (or an
        # implied midpoint between two off-curve points).
        ex, ey, eon = pts[(i + 2) % n]
        if not eon:
            ex, ey = (nx + ex) / 2, (ny + ey) / 2
        for s in range(1, CURVE_STEPS):
            t = s / CURVE_STEPS
            out.append(((1 - t) ** 2 * x + 2 * (1 - t) * t * nx + t * t * ex,
                        (1 - t) ** 2 * y + 2 * (1 - t) * t * ny + t * t * ey))
        i += 2 if eon else 1
    return out


def main(font_path):
    font = TTFont(font_path)
    glyf = font["glyf"]
    skew = math.tan(math.radians(-font["post"].italicAngle))
    polys = {}
    for seg, name in SEGMENTS.items():
        polys[seg] = [(x - y * skew, y) for x, y in flatten(contour_points(glyf, name))]

    allpts = [p for poly in polys.values() for p in poly]
    x0, x1 = min(p[0] for p in allpts), max(p[0] for p in allpts)
    y0, y1 = min(p[1] for p in allpts), max(p[1] for p in allpts)

    lines = [
        "// Generated by tools/gen_segments.py; do not edit by hand.",
        "// Segment outlines from the \"7-Segment\" font by Jan Bobrowski (~jb),",
        "// (https://torinak.com/font/7-segment), SIL Open Font License 1.1,",
        "// de-skewed to upright. Coordinates are 0..1000, y = 0 at the top.",
        "#pragma once",
        "",
    ]
    for seg, poly in polys.items():
        norm = [(round((x - x0) / (x1 - x0) * 1000), round((y1 - y) / (y1 - y0) * 1000))
                for x, y in poly]
        flat = ", ".join("%d, %d" % p for p in norm)
        lines.append("static const int16_t SEG_POLY_%s[] = { %s };" % (seg, flat))
    lines += [
        "",
        "static const int16_t *const SEG_POLYS[7] = {",
        "  SEG_POLY_A, SEG_POLY_B, SEG_POLY_C, SEG_POLY_D, SEG_POLY_E, SEG_POLY_F, SEG_POLY_G,",
        "};",
        "static const uint8_t SEG_POLY_LEN[7] = { %s };"
        % ", ".join(str(len(polys[s])) for s in "ABCDEFG"),
        "",
    ]
    out = Path(__file__).resolve().parent.parent / "src/c/segments.h"
    out.write_text("\n".join(lines))
    print("wrote", out)


if __name__ == "__main__":
    main(sys.argv[1])
